name: base_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  micro_core:
    git:
      url: https://github.com/kindaniel/micro_core.git
      ref: main  

  micro_app_login:
    git:
      url: https://github.com/kindaniel/micro_app_login.git
      ref: main  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

